name: Add to Project Board

on:
  workflow_dispatch:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add event issues to All GitHub Events Board
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@main
        with: 
          project-url: https://github.com/users/shmeadyy/projects/2/views/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: low-intent-event, high-intent-event
          label-operator: OR
